owner: tomssbayezon
repo: bayezon-status

sites:
  - name: CityBeach Storefront Loader
    url: https://prod-sunny.bayezon.ai/loader.js
  - name: Rodd & Gunn Storefront Loader
    url: https://roddandgunn-product-loader.bayezon.com/loader.js
  - name: Rodd & Gunn Failing Loader
    url: https://roddandgunn-loader.bayezon.com/loader.js

status-website:
  baseUrl: /bayezon-status
  name: Bayezon
  introTitle: "**Bayezon** service status"
  introMessage: Live status of Bayezon platform services.
  theme: light
  navbar:
    - title: Status
      href: /
